version: '2.2'

services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: filter_ez
      POSTGRES_PASSWORD: filter_ez
      POSTGRES_DATABASE: filter_ez
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  app:
    restart: always
    build:
       context: .
       dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1 
      DOCKER: 1
      PYTHONUNBUFFERED: 0
    volumes:
      - ./filter_ez:/filter_ez
    ports:
      - 8000:8000
    depends_on: 
      - rabbitmq
      - postgres
      - redis
    entrypoint: ["python3.6", "run.py"]

  redis:
    image: "redis"
    container_name: carstatistics_redis
    volumes:
    - ./redis:/var/lib/redis/data
    ports:
    - 6379

  celery:
    build: .
    entrypoint: ["celery", "worker", "-l", "info", "-A", "app.CELERY", "-Q", "general"]
    environment:
      C_FORCE_ROOT: "True"
      DOCKER: 1
    volumes:
      - './filter_ez:/filter_ez'
    depends_on:
      - rabbitmq
      - redis
    scale: 3
